# Generated by Django 4.2 on 2024-10-16 06:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="phone",
            field=models.CharField(
                help_text="Укажите 11 цифр Вашего номера телефона, пример: 70000000001",
                max_length=11,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Номер телефона должен состоять из 11 цифр.",
                        regex="^\\d{11}$",
                    )
                ],
                verbose_name="Номер телефона",
            ),
        ),
    ]
