# Generated by Django 4.2 on 2024-10-16 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_user_phone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="invite_code",
            field=models.CharField(
                help_text="Автоматически генерируется при регистрации",
                max_length=6,
                unique=True,
                verbose_name="Инвайт-код",
            ),
        ),
    ]
